# Generated by Django 5.2.6 on 2025-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthormodel',
            name='full_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='full_name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
